# Generated by Django 4.1.3 on 2022-12-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_address_alter_customuser_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'ユーザー情報'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='burakku',
            field=models.BooleanField(default=False),
        ),
    ]
