# Generated by Django 4.1.3 on 2022-12-07 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_siyouritu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='day',
            field=models.DateField(default='timezone.now', verbose_name='日付'),
        ),
    ]
