# Generated by Django 4.1.3 on 2022-12-12 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_news_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name_plural': '予約状況'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'お知らせ'},
        ),
        migrations.AlterModelOptions(
            name='siyouritu',
            options={'verbose_name_plural': '予約トータル件数'},
        ),
        migrations.AlterModelOptions(
            name='zaseki',
            options={'verbose_name_plural': '座席'},
        ),
    ]
